In [ ]:
# We import Numpy with its abbreviation "np"
import numpy as np

In [ ]:
# We can create one-dimensional arrays with the np.array() function
array_1d = np.array([1, 2, 3, 4, 5])

# Or a two-dimensional array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Or a three-dimensional array
array_3d = np.array([[[1, 2, 3],
                     [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]]])

# Numpy library practice

In this notebook, a series of tasks will be developed using the Numpy (Numerical Python) library.

We propose and document possible ways to solve the exercises, but those are not the only ways to do it.

It is always a good idea to check the [Official Numpy Documentation](https://numpy.org/devdocs/user/index.html), where it is possible to find all kinds of information about this library. And if you get stuck, search on Google "how to do [something] with Numpy". There's a good chance that question has already been answered!

For each of these arrays, we can get its properties, such as its "shape", number of dimensions, data types and size.

In [ ]:
# Attributes of the one-dimensional array (shape, number of dimensions, data types, size and type)
array_1d.shape, array_1d.ndim, array_1d.dtype, array_1d.size, type(array_1d)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [ ]:
# Two-dimensional array attributes
array_2d.shape, array_2d.ndim, array_2d.dtype, array_2d.size, type(array_2d)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [ ]:
# Attributes of the three-dimensional array
array_3d.shape, array_3d.ndim, array_3d.dtype, array_3d.size, type(array_3d)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [ ]:
# We import pandas as pd, and create a DataFrame from the two-dimensional array
import pandas as pd

data = pd.DataFrame(array_2d)
data

0  1  2
0  1  2  3
1  4  5  6

In [ ]:
# We create an array of size 4x3, formed only by ones (1)
ones = np.ones((4, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# We create an array of size 2x4x3, consisting only of zeros (0)
zero = np.zeros((2, 4, 3))
zero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# We create an array of numbers in the range 0 to 100, jumping from 5 to 5
array_1 = np.arange(0, 101, 5)
array_1

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [ ]:
# We create an array of random integer numbers between 0 and 10, of size (2, 5)
array_2 = np.random.randint(0, 10, (2, 5))
array_2

array([[7, 9, 2, 3, 3],
       [0, 8, 5, 9, 1]])

In [ ]:
# We create an array of decimal random numbers between 0 and 1, of size (3, 5)
array_3 = np.random.random((3, 5))
array_3

array([[0.17564542, 0.38262232, 0.01545591, 0.49506026, 0.43384087],
       [0.94123077, 0.33107066, 0.33886194, 0.85664865, 0.92236199],
       [0.45289496, 0.08645989, 0.94260302, 0.41065198, 0.50337409]])

In [ ]:
# We set the "seed" of random numbers at 27
np.random.seed(27)

# We create an array of integer random numbers between 0 and 10, of size (3, 5)
array_4 = np.random.randint(0, 10, (3, 5))
array_4

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2],
       [1, 1, 4, 6, 3]])

What happens when you run the last cell again, unlike the previous cells?

In [ ]:
# We find the unique values of array_4
np.unique(array_4)

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [ ]:
# We extract the element at index 1 from array_4
array_4[1]

array([5, 8, 9, 1, 2])

In [ ]:
# We extract the first two rows from array_4
array_4[:2]

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2]])

In [ ]:
# We extract the first two items of the first two rows of the array_4
array_4[:2, :2]

array([[3, 8],
       [5, 8]])

In [ ]:
# We create two arrays of size 3x4: one filled with random numbers between 0 and 10, and the other filled with ones
array_5 = np.random.randint(0, 10, (3, 4))
array_6 = np.ones((3, 4))

In [ ]:
# We call the array_5
array_5

array([[3, 0, 5, 3],
       [3, 6, 7, 2],
       [7, 8, 5, 7]])

In [ ]:
# We call the array_6
array_6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# We add the two arrays together
array_5 + array_6

array([[4., 1., 6., 4.],
       [4., 7., 8., 3.],
       [8., 9., 6., 8.]])

In [ ]:
# We now create an array of size (4, 3) filled with ones
array_7 = np.ones((4, 3))
array_7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# We will try to sum arrays 6 and 7
array_6 + array_7

ValueError: ignored

What is the reason for the above error and what should we take into account to prevent it from happening?

In [ ]:
# We will then create another array of size (4, 3) filled with ones.
array_8 = np.ones((4, 3))
array_8

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# We subtract array_8 from array_7
array_8 - array_7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# We create another two arrays of size 3x3 with random numbers from 1 to 5
array_9 = np.random.randint(1, 5, (3, 3))
array_10 = np.random.randint(1, 5, (3, 3))

In [ ]:
# We call the array_9
array_9

array([[2, 3, 4],
       [1, 4, 4],
       [2, 3, 4]])

In [ ]:
# We call the array_10
array_10

array([[2, 1, 4],
       [4, 1, 2],
       [2, 4, 1]])

In [ ]:
# We multiply the last two arrays with each other
array_9 * array_10

array([[ 4,  3, 16],
       [ 4,  4,  8],
       [ 4, 12,  4]])

In [ ]:
# We square the array_9
array_9 ** 2

array([[ 4,  9, 16],
       [ 1, 16, 16],
       [ 4,  9, 16]])

In [ ]:
# We look for the square root of array_10
np.sqrt(array_10)

array([[1.41421356, 1.        , 2.        ],
       [2.        , 1.        , 1.41421356],
       [1.41421356, 2.        , 1.        ]])

In [ ]:
# We find the average of the values of array_9
array_9.mean()

3.0

In [ ]:
# We find the maximum of the values in array_9
array_9.max()

4

In [ ]:
# We find the minimum of the values in array_9
array_9.min()

1

In [ ]:
# We change the shape of the array_9 to a 9x1 array, and store it as array_11
array_11 = array_9.reshape(9, 1)

In [ ]:
# We call the array_11
array_11

array([[2],
       [3],
       [4],
       [1],
       [4],
       [4],
       [2],
       [3],
       [4]])

In [ ]:
# We transpose the array_11
array_11.T

array([[2, 3, 4, 1, 4, 4, 2, 3, 4]])

In [ ]:
# We compare array_9 and array_10, to know which elements of array_9 are greater than those of array_10
array_12 = array_9 > array_10
array_12

array([[False,  True, False],
       [False,  True,  True],
       [False, False,  True]])

What types of data are part of the result array?

In [ ]:
# Let's look at its new data types
array_12.dtype

dtype('bool')

In [ ]:
# Is any of the elements of array_9 equal to its equivalent in array_10?
array_9 == array_10

array([[ True, False,  True],
       [False, False, False],
       [ True, False, False]])

In [ ]:
# We compare again both arrays, this time with >=
array_9 >= array_10

array([[ True,  True,  True],
       [False,  True,  True],
       [ True, False,  True]])

In [ ]:
# We look for the elements of array_9 that are greater than 2
array_9 > 2

array([[False,  True,  True],
       [False,  True,  True],
       [False,  True,  True]])

In [ ]:
# We order the elements inside the array_9 from smallest to largest 
np.sort(array_9)

array([[2, 3, 4],
       [1, 4, 4],
       [2, 3, 4]])